#配置数据源
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf8
     username: root
     password: admin
     driver-class-name: com.mysql.jdbc.Driver
  dubbo:
    application.name: provider #提供方应用信息，用于计算依赖关系
    registry.address: zookeeper://127.0.0.1:2181  #使用zookeeper广播注册中心暴露服务地址
    protocol.name: dubbo    #用dubbo协议在20880端口暴露服务
    protocol.port: 20880
    scan: com.dubbo.dubbodemo.service
#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dubbo.dubbodemo.entity  # 注意：对应实体类的路径


